name: Update Profile README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 21 7 *' # Runs at 00:00 UTC on July 21 every year

jobs:
  update-profile-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v4
        with:
          repository: TheFlash91/TheFlash91
          token: ${{ secrets.GH_PATH_TOKEN }}
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: TheFlash91/TheFlash91
          path: source
          token: ${{ secrets.GH_PATH_TOKEN }}
      - name: Copy README
        run: cp source/readme.md ./README.md
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update profile README" || exit 0
          git push