name: Update Age in README

on:
  schedule:
    - cron: '0 0 21 7 *' # Runs at 00:00 UTC on July 21 every year
  workflow_dispatch:

jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node update-age.js
      - name: Commit changes
        env:
          GH_PATH_TOKEN: ${{ secrets.GH_PATH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add readme.md
          git commit -m "Update age in README" || exit 0
          git push https://x-access-token:${GH_PATH_TOKEN}@github.com/${{ github.repository }} HEAD:main